minimum_pre_commit_version: "2.9.0"
exclude: ^(mosquitto/mosquitto.conf)

repos:
  - repo: "https://github.com/golangci/golangci-lint"
    rev: "v1.52.2"
    hooks:
      - id: golangci-lint

  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.4.0"
    hooks:
      - id: "end-of-file-fixer"
      - id: "trailing-whitespace"
      - id: "check-merge-conflict"

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.3
    hooks:
      - id: gitleaks
        stages: [manual, push]
